[package]
name = "rustvani"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio           = { version = "1", features = ["full"] }
async-trait     = "0.1"
thiserror       = "1"
futures         = "0.3"
log             = "0.4"
env_logger      = "0.11"
ort = { version = "2.0.0-rc.12", features = ["download-binaries"] }
ndarray         = "0.17"
async-recursion = "1"

[dev-dependencies]
tokio      = { version = "1", features = ["full", "test-util"] }
env_logger = "0.11"
